services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=base'
      - 'MYSQL_PASSWORD=base'
      - 'MYSQL_ROOT_PASSWORD=base'
      - 'MYSQL_USER=base'
    ports:
      - '3307:3306'
